Resolves #45 - Added example to traverse scene graph
dust-engine/dot_vox pull request #51
Opened 2024-09-13 15:54 UTC by davids91

2024-09-16 09:29 UTC, Neo-Zhixing requested changes

2024-09-16 09:29 UTC, PixelDust22 commented on Cargo.toml
> +nalgebra = "^0.33" # for the traverse_graph example
For matrix multiplication we already have `glam`. Would be great if you can use that?

2024-09-16 09:29 UTC, PixelDust22 commented on Cargo.toml
> +[[example]]
There's no need to add an `[[example]]` section. Just put it in the `examples` directory, and cargo will infer that it's there, and you can run the example using `cargo run --example traverse_graph`

2024-09-16 09:29 UTC, PixelDust22 commented on examples/traverse_graph.rs
> +fn parse_rotation_matrix(b: u8) -> Matrix3<i8> {
We already have something that does the conversion in https://github.com/dust-engine/dot_vox/blob/726089da3a4f67c882bd503efe0bab4ed7ae387a/src/types.rs#L28-L33 . Maybe you can use that instead?

2024-09-16 10:56 UTC, davids91 commented on Cargo.toml
> +[[example]]
It was a remnant of me trying to restrict the `nalgebra` dependency to the example; Will revert that for sure

2024-09-16 17:00 UTC, davids91 commented on examples/traverse_graph.rs
> +fn parse_rotation_matrix(b: u8) -> Matrix3<i8> {
Sure thing!

2024-09-16 17:01 UTC, davids91 commented
It would be possible to extend the library interface with the `fn transform` implemented in the example, would it be desirable? It's not used within the library, but would be great to have for the consumers

2024-10-10 08:01 UTC, PixelDust22 requested changes

2024-10-10 08:01 UTC, PixelDust22 commented on Cargo.toml
> +glam = "0.21"
We do want a trailing empty line here. Try not to modify files you did not touch

2024-10-10 08:01 UTC, PixelDust22 commented on examples/traverse_graph.rs
> +    while 0 < node_stack.len() {
!node_stack.is_empty()

2024-10-10 08:01 UTC, PixelDust22 commented on examples/traverse_graph.rs
> +    let matrix = rotation.to_cols_array_2d();
A better way to do this might be converting this into a `glam::Mat3` using [this](https://docs.rs/glam/latest/glam/f32/struct.Mat3.html#method.from_cols_array_2d). Then you can directly multiply the `glam::Mat3` with the `Vec3`.

No need to create a separate function for this - you can just do it inline.

2024-10-10 08:01 UTC, PixelDust22 commented on examples/traverse_graph.rs
> +fn iterate_vox_tree<F: FnMut(&Model, &Vec3, &Rotation) -> ()>(vox_tree: &DotVoxData, mut fun: F) {
nit: you can just write 
```suggestion
fn iterate_vox_tree(vox_tree: &DotVoxData, mut f: impl FnMut(&Model, &Vec3, &Rotation)) {
```

2024-10-10 08:01 UTC, PixelDust22 commented on examples/traverse_graph.rs
> +                    node_stack.pop();
Correct me if I'm missing something, but I don't think index==1 was ever pushed into the node_stack. Are you sure you need this code path?

2024-10-10 08:01 UTC, Neo-Zhixing commented on examples/traverse_graph.rs
> +    // An iterator for each level of depth, during depth-first search:
Iterator has a specific meaning in Rust. A better description might be
```suggestion
// The stack for maintaining iteration state.
```

2024-10-10 08:04 UTC, Neo-Zhixing commented
Thanks for switching over to glam! There are still some problems with the example code. If you could fix them this should be ready to merge.

2024-10-10 13:39 UTC, davids91 commented on examples/traverse_graph.rs
> +                    node_stack.pop();
It's updated at 
https://github.com/dust-engine/dot_vox/blob/10f6063a3e8c10b4400e8842e00ef644adfdae4a/examples/traverse_graph.rs#L64

I'll extend the comments to document this logic

2024-10-15 15:19 UTC, Neo-Zhixing approved these changes
Thank you!

2024-10-15 15:19 UTC, merged